2024-12-01 02:24:51,320 - root - WARNING - Не удалось прочитать файл /Users/michaotic/Documents/GitHub/fast-api-evraz/.DS_Store: 'utf-8' codec can't decode byte 0x80 in position 3131: invalid start byte
2024-12-01 02:24:51,325 - root - WARNING - Не удалось прочитать файл /Users/michaotic/Documents/GitHub/fast-api-evraz/app/core/analysis/__pycache__/tree_parser.cpython-311.pyc: 'utf-8' codec can't decode byte 0xa7 in position 0: invalid start byte
2024-12-01 02:24:51,326 - root - WARNING - Не удалось прочитать файл /Users/michaotic/Documents/GitHub/fast-api-evraz/app/core/analysis/__pycache__/__init__.cpython-311.pyc: 'utf-8' codec can't decode byte 0xa7 in position 0: invalid start byte
2024-12-01 02:24:51,327 - root - WARNING - Не удалось прочитать файл /Users/michaotic/Documents/GitHub/fast-api-evraz/app/core/utils/__pycache__/pdf_generator.cpython-311.pyc: 'utf-8' codec can't decode byte 0xa7 in position 0: invalid start byte
2024-12-01 02:24:51,327 - root - WARNING - Не удалось прочитать файл /Users/michaotic/Documents/GitHub/fast-api-evraz/app/core/utils/__pycache__/unzip.cpython-311.pyc: 'utf-8' codec can't decode byte 0xa7 in position 0: invalid start byte
2024-12-01 02:24:51,327 - root - WARNING - Не удалось прочитать файл /Users/michaotic/Documents/GitHub/fast-api-evraz/app/core/utils/__pycache__/__init__.cpython-311.pyc: 'utf-8' codec can't decode byte 0xa7 in position 0: invalid start byte
2024-12-01 02:24:51,328 - root - WARNING - Не удалось прочитать файл /Users/michaotic/Documents/GitHub/fast-api-evraz/app/core/__pycache__/config.cpython-311.pyc: 'utf-8' codec can't decode byte 0xa7 in position 0: invalid start byte
2024-12-01 02:24:51,328 - root - WARNING - Не удалось прочитать файл /Users/michaotic/Documents/GitHub/fast-api-evraz/app/core/__pycache__/logger.cpython-311.pyc: 'utf-8' codec can't decode byte 0xa7 in position 0: invalid start byte
2024-12-01 02:24:51,329 - root - WARNING - Не удалось прочитать файл /Users/michaotic/Documents/GitHub/fast-api-evraz/app/__pycache__/main.cpython-311.pyc: 'utf-8' codec can't decode byte 0xa7 in position 0: invalid start byte
2024-12-01 02:24:51,330 - root - WARNING - Не удалось прочитать файл /Users/michaotic/Documents/GitHub/fast-api-evraz/app/api/v1/endpoints/__pycache__/router.cpython-311.pyc: 'utf-8' codec can't decode byte 0xa7 in position 0: invalid start byte
2024-12-01 02:24:51,330 - root - WARNING - Не удалось прочитать файл /Users/michaotic/Documents/GitHub/fast-api-evraz/app/api/v1/endpoints/__pycache__/__init__.cpython-311.pyc: 'utf-8' codec can't decode byte 0xa7 in position 0: invalid start byte
2024-12-01 02:52:03,874 - root - WARNING - Не удалось прочитать файл /Users/michaotic/Documents/GitHub/fast-api-evraz/.venv/lib/python3.9/site-packages/joblib/test/test_func_inspect_special_encoding.py: 'utf-8' codec can't decode byte 0xa4 in position 64: invalid start byte
2024-12-01 04:51:06,612 - root - ERROR - Ошибка при запуске flake8: no path specified
2024-12-01 04:53:02,502 - root - ERROR - Ошибка при запуске flake8: no path specified
